version: '3.8'
services:
  angular-app:
    build:
      context: .
      dockerfile: apps/angular-app/Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend-backend

  express-service:
    build:
      context: .
      dockerfile: apps/express-service/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend-backend

networks:
  frontend-backend:
    driver: bridge
