version: '3.8'
services:
  angular-app:
    image: pavelkostenko/angular-app:latest
    ports:
      - "80:80"
    networks:
      - frontend-backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: on-failure

  express-service:
    image: pavelkostenko/express-service:latest
    ports:
      - "3000:3000"
    networks:
      - frontend-backend
    deploy:
      replicas: 5
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: on-failure

networks:
  frontend-backend:
    external: true
    name: frontend-backend
